### ISSUE TITLE
Error in line 130

### ISSUE THREAD

**Issue by gerjul** [nicomontes/AutoTrain#1]
Hello Nicomontes,

I get this error during the connection to my google account.
It seems that $totp = ROTP::TOTP.new(pin) line does not pass.
Is it because i set a wrong google_pin value?
I used the one google texted me when i tried to modified my number from google account settings.

Connection with xxx.xxx@gmail.com
Traceback (most recent call last):
	7: from bookTrainline.rb:143:in `<main>'
	6: from bookTrainline.rb:123:in `connect_me'
	5: from /usr/local/lib/ruby/gems/2.5.0/gems/watir-6.14.0/lib/watir/window.rb:183:in `use'
	4: from /usr/local/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/common/target_locator.rb:70:in `window'
	3: from bookTrainline.rb:130:in `block in connect_me'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/watir-6.14.0/lib/watir/elements/element.rb:129:in `click'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/watir-6.14.0/lib/watir/elements/element.rb:756:in `element_call'
/usr/local/lib/ruby/gems/2.5.0/gems/watir-6.14.0/lib/watir/elements/element.rb:767:in `rescue in element_call': timed out after 30 seconds, waiting for #<Watir::Span: located: true; {:text=>"Suivant", :tag_name=>"span"}> to be located; Maybe look in an iframe? (Watir::Exception::UnknownObjectException)

my computer run under MacOSX
Any idea ?
Thank's in advance.

**Comment by n5s6** [comment]
Hey,

You need to use 2 factor authentification with your google account.
You can't set a wrong pin.

You are welcome !

**Comment by n5s6** [comment]
I update my code and you can set your pin with nothing -> ''.
